Gyro Join/Exit
balancer/b-sdk pull request #121
Opened 2023-11-08 22:30 UTC by lgahdl

Using the WeightedJoin and WeightedExit, but filtering unsupported join/exit kinds in the validateInputs method.
Adding tests.

2023-11-09 13:36 UTC, johngrantuk commented on src/entities/exit/poolExit.ts
> +            GYRO2: new WeightedExit(),
Could we add a comment here explaining what Exits Gyro supports

2023-11-09 13:37 UTC, johngrantuk commented on src/entities/join/poolJoin.ts
> +            GYRO2: new WeightedJoin(),
Could we add a comment here explaining what Joins Gyro supports

2023-11-09 13:38 UTC, johngrantuk requested changes
Nice to reuse the Weighted logic!
Can we add integration tests for the other gyro pool types please.

2023-11-10 00:14 UTC, lgahdl commented
> Nice to reuse the Weighted logic! Can we add integration tests for the other gyro pool types please.

Couldn't add tests with native assets because there are no GyroE V1, Gyro2 and Gyro3 pools with wrapped native assets in any network :/

2023-11-10 09:20 UTC, johngrantuk commented on test/gyro3Exit.integration.test.ts
> +            type: 'GYRO2',
Needs to be changed to test properly

2023-11-10 09:21 UTC, johngrantuk commented on test/gyro3Join.integration.test.ts
> +            type: 'GYRO2',
Needs to be changed to test properly

2023-11-10 14:24 UTC, johngrantuk commented
@lgahdl - notice changes made to buildCall outputs [here](https://github.com/balancer/b-sdk/pull/123). You'll need to also update this PR.

2023-11-10 20:39 UTC, lgahdl commented
> @lgahdl - notice changes made to buildCall outputs [here](https://github.com/balancer/b-sdk/pull/123). You'll need to also update this PR.

I merged the branch, everything working fine, the Gyro pools are using the WeightedJoin and WeightedExit.

2023-11-10 20:41 UTC, lgahdl commented on test/gyro3Join.integration.test.ts
> +            type: 'GYRO2',
No, just fixed it, thanks!

2023-11-10 20:41 UTC, lgahdl commented on test/gyro3Exit.integration.test.ts
> +            type: 'GYRO2',
No, sorry, didn't see that

2023-11-13 11:53 UTC, johngrantuk approved these changes
LGTM!

2023-11-13 18:53 UTC, merged